[default_session]
startup_command = "nvim"

[[session]]
path = "~/coding/gns3util"
name = "gns3test"
startup_command = '''
tmux send-keys "nvim ." C-m
tmux split-window -v -c "~/coding/gns3util"
tmux new-window -c "~/coding/gns3util"
tmux new-window -c "~/coding/gns3util_ermgamba"
tmux new-window -c "~/github/gns3-review/main_repo_mit_prs/gns3-api-util"
tmux new-window -c "~/coding/gns3-api-util"
tmux new-window -c "~/github/bucket"
tmux new-window -c "~/github/homebrew-tap"
tmux new-window -c "~/github/gns3util"
tmux new-window -c "~/coding/temp/temp2/temp3/temp4/gns3-api-util"
tmux select-window -t 1
'''

[[session]]
path = "~/coding/uuhcordWrapped"
name = "uuhcordWrapped"
startup_command = '''
tmux send-keys "nvim ." C-m
tmux new-window -c "~/coding/uuhcordWrapped"
tmux new-window -c "~/coding/uuhcordWrapped"
tmux new-window -c "~/coding/uuhcordWrapped"
tmux select-window -t 1
'''

[[session]]
path = "~/coding/privacyViolation"
name = "privacyViolation"
startup_command = '''
tmux send-keys "nvim ." C-m
tmux new-window -c "~/coding/privacyViolation"

tmux split-window -h -c "~/coding/privacyViolation"

tmux new-window -c "~/coding/privacyViolation"
tmux new-window -c "~/coding/privacyViolation"
tmux select-window -t 1
'''

[[session]]
path = "~/coding/codeberg/ermokie"
name = "ermokie"
startup_command = '''
tmux send-keys "nvim ." C-m

tmux new-window -c "~/coding/codeberg/ermokie"
tmux split-window -v -c "~/coding/codeberg/ermokie"

tmux new-window -c "~/.local/share/ermokie"
tmux select-window -t 1
'''

[[session]]
path = "~/dotfiles"
name = "dotfiles"
startup_command = '''
tmux send-keys "nvim ." C-m
tmux new-window -c "~/dotfiles"
tmux new-window -c "~/dotfiles"
tmux new-window -c "~/dotfiles"
tmux select-window -t 1
'''

[[session]]
path = "~/.config/nvim"
name = "nvim"
startup_command = '''
tmux send-keys "nvim ." C-m
tmux new-window -c "~/.config/nvim"
tmux select-window -t 1
'''
